import { Footer, Header } from '@/components/layout'
import { cn } from '@/utils/tw'
import { Analytics } from '@vercel/analytics/react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PPhim',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'flex h-screen flex-col')}>
        <Header />
        <main className="flex-1 bg-[#181818] py-20">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  )
}
